### ISSUE TITLE
FetchAPI

### ISSUE THREAD

**Issue by whitphx** [Kitanotori/react-webpack-babel-hotreload-example#4]
https://github.com/Kitanotori/react-webpack-babel-hotreload-example/blob/61b528934aff277a9d66da9acf530d51160fa8b3/src/reducers/async_fetch_reducer.js#L29

Fetch API is currently just experimental ( https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API ).
I think it is better to use polyfill ( https://github.com/github/fetch ) or other ajax libs (e.g. [superagent](https://github.com/visionmedia/superagent) )

**Comment by nakamorichi** [comment]
In production app, it is recommended to use polyfill, and whatwg-fetch is the one I also use in production. However, the original purpose of this sample wasn't to address cross-browser compatibility issues (well, mainly IE).
