### ISSUE TITLE
ERROR in main-3aab2ce95a9cac16845f.js from UglifyJs

### ISSUE THREAD

**Issue by zhengjunxiang** [Kitanotori/react-webpack-babel-hotreload-example#5]
When I use the command `npm run bundle`;
get some error messages
`ERROR in main-3aab2ce95a9cac16845f.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [main-3aab2ce95a9cac16845f.js:40,37]
`
What‘s wrong with it?

**Comment by nakamorichi** [comment]
Should be fixed now.
